name: feelback
channels:
  - conda-forge
  - defaults
dependencies:
  - dlib=19.24.0
  - flask=2.1.2
  - flask-cors=3.0.10 
  - matplotlib=3.5.2
  - numpy=1.22.3
  - opencv=4.5.5
  - pandas=1.4.2
  - python-dotenv=0.20.0 
  - python-magic=0.4.25
  - scikit-image=0.19.2
  - scikit-learn=1.1.1
