name: feelback
channels:
  - conda-forge
  - defaults
dependencies:
  - dlib=19.24.0
  - flask=2.1.2
  - flask-cors=3.0.10 
  - flask-sqlalchemy=2.5.1
  - matplotlib=3.5.2
  - numpy=1.22.4
  - opencv=4.5.5
  - pandas=1.4.2
  - psycopg2=2.9.3
  - python-dotenv=0.20.0
  - pymysql=1.0.2
  - scikit-image=0.19.2
  - scikit-learn=1.1.1
  - sqlalchemy=1.4.36
  - sqlalchemy-utils=0.38.2
  - sqlite=3.38.5
