name: feelback
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.5.1
  - numpy=1.22.2
  - opencv=4.5.5
  - pandas=1.4.1
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
