name: feelback
channels:
  - conda-forge
  - defaults
dependencies:
  - dlib=19.24.0
  - matplotlib=3.5.2
  - numpy=1.22.3
  - opencv=4.5.5
  - pandas=1.4.2
  - scikit-image=0.19.2
  - scikit-learn=1.1.1
  - ffmpeg
